[build]
  # Build command
  command = "npm run build"
  
  # Directory to publish (Vite outputs to dist by default)
  publish = "dist"
  
  # Node.js version
  environment = { NODE_VERSION = "18" }

# Handle client-side routing (SPA redirects)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers for better performance and security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache HTML with shorter duration
[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Handle API routes if any (optional - remove if not needed)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Environment variables (uncomment and configure as needed)
# [build.environment]
#   NODE_ENV = "production"
#   VITE_APP_TITLE = "100 Days Discipline Challenge"